### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by danfascia** [botwayorg/pocketbase#1]
I've also gone this far with Pocketbase on Railway.app but the main issue is lack of persistent storage so you lose all of your data on every deploy.

A solution implementing [Litestream](https://litestream.io/) into the Docker image could sort this problem out and make Railway a very appealing place to deploy pocketbase

**Comment by abdfnx** [comment]
Hi @danfascia, Yes I was trying to solve this issue from a long time, but don't worry, when I finish work on [botway](https://github.com/abdfnx/botway), I will fix it 👍

**Comment by abdfnx** [comment]
@danfascia, botway team created a project called [**strg**](https://github.com/botwayorg/strg), this program that syncs database files located in a Docker container under your GitHub account, just add `GITHUB_TOKEN` env var and deploy pocketbase template 👍
